export { VectorlessClient } from "./client.js";
export type {
  VectorlessConfig,
  AddDocumentOptions,
  AddDocumentResponse,
  ToCManifest,
  ToCEntry,
  ToCTreeNode,
  ToCTreeManifest,
  PageRange,
  Section,
  SectionSummary,
  DocumentSummary,
  DocumentDetail,
  ListDocumentsOptions,
  ListDocumentsResponse,
  WaitForReadyOptions,
  TreeQueryOptions,
  TreeQueryResult,
  TraversalStep,
} from "./types.js";
export {
  VectorlessError,
  AuthenticationError,
  NotFoundError,
  RateLimitError,
  ValidationError,
  ConflictError,
  ServerError,
} from "./errors.js";
